### ISSUE TITLE
Clarification on the knloader.bdt file

### ISSUE THREAD

**Issue by remy** [kounch/knloader#1]
Not sure if you prefer issue here or FB, but starting here for now.

I suspect my own issue is not quite following the manual properly (and I'd be happy to help the docs via PR if you like).

The manual says

> Create knloader.bdt file (see below for more instructions).

But then below is reads "navigate to where … knloader.bdt are" - yet the file doesn't exist as part of the release (so I'm guessing I've got the wrong part).

The next section is called "Database file format" - it's descriptive, but I wasn't sure if this meant I should write this file myself or if this is how it was generated (and from the earlier instructions I thought it would be generated).

This section states the first line must be the root path (in my case `/ROMS`) - so I thought to create the file knloader.bdt with `/ROMS\n`, but this caused errors in the loader (`2\t6410`).

So if the file does need to be created manually, the first line is the search path, but the path for the game is included in the record, so I wasn't sure if this was relative or absolute, i.e.

```
/ROMS
Batman,4,/ROMS/Batman/,Batman.tap
```

Or if it's 

```
/ROMS
Batman,4,/Batman/,Batman.tap
```

I do feel like I've just got the manual wrong (but again, I'd be happy to help propose any changes to help clarify for simpletons like me!)

**Comment by kounch** [comment]
There are already some changes at develop branch including more instructions and an example (see manual_en.adoc file)

I will expand them with a more detailed explanation 

Thanks for your feedback!

**Comment by kounch** [comment]
So the idea is as follows:

1.Create manually your .dbt file
2.Copy it to the SD, to the same path where the .bas file is.
3.Enjoy

The way it is parsed is like this:
1. Read the root path (first line of file)
2. Read the info for each file, including a subpath
3. When looking for the .tap, etc or image file, use the root path plus the subpath 

So

`/ROMS`
`MyGame,2,MyPath/MyTapeDir,MyTape.tap`

Means that the program will look for 
`/ROMS/MyPath/MyTapeDir/MyTape.tap` 

when you select “MyGame”

Current version does not admit a blank subpath, but beta 2 (already on `develop` branch) will allow it.

**Comment by remy** [comment]
Great, thank you. 

Like I said on FB, I'd been thinking of something similar but just didn't have the time to even start, so you e saved me the job 😊.

I *think* it might be possible to generate the database file automatically (using `.find`) - I've already explored ways to do it, but I think I'd only be able to get the game name out of .tap files (though I've not investigated the other formats yet. If I actually manage to automate this, I'd be happy to throw the code your way.

Thanks again.

**Comment by kounch** [comment]
After the tests i have already made, i was more inclined to use CAT and explore the directories recursively. 

The problem i have with .find is that i would have to call it for every kind of file i want to process, and the list is growing:

*.TAP
*.TZX
*.BAS
*.NEX
*.SNX
*.SNA
*.Z80
*.DSK
DISK.
*.BMP
*.SCR
*.SCL
...etc

**Comment by remy** [comment]
Sod, you're right.

I think I gravitated towards find because I've got all my games in
subdirectories and they're nearly all .tap files.

**Comment by remy** [comment]
I wrote a bash shell to get this generated for me - https://gist.github.com/remy/4913bdb6b3f8d5901016b050216382b1 - it's mac specific (which is a bit naff), but I posted it on the FB group in case anyone else can benefit from it.

**Comment by kounch** [comment]
Version 0.2 beta is out, with an expanded manual including examples.
